version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - cd $FOLDER_PATH # do nothing here for now
      - npm install
      - npm install -g serverless
  #pre_build:
  #  commands:
      #- cd $FOLDER_PATH # do nothing here for now
      # - rm -rf ./build
      # - npx yarn build
  build:
    commands:
      - serverless deploy --stage $STAGE --aws-region $AWS_REGION --force --verbose
  post_build:
    commands:
      - echo Build completed on `date`
      # - if [ "$CODEBUILD_BUILD_SUCCEEDING" -eq 1 ]; then npx yarn postdeploy:$STAGE; else npx yarn postdeploy:failed:$STAGE; fi