version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npx yarn
  pre_build:
    commands:
      - rm -rf ./build
      - npx yarn build
  build:
    commands:
      - npx yarn sls deploy --stage $STAGE --force --verbose
  post_build:
    commands:
      - if [ "$CODEBUILD_BUILD_SUCCEEDING" -eq 1 ]; then npx yarn postdeploy:$STAGE; else npx yarn postdeploy:failed:$STAGE; fi